We will learn using the Facebook AI Similarity Search Database. Likewise we will also look other Database. FAISS is an open source database.

We will first create an environment. For this we will install conda distribution. There is also another diostribution called uv which is very good dependency resolver. UV will be discussed later on.

We want to use python 3.10 so use:    conda create -n vectorDB python=3.10

To activate an environment: conda activate vectorDB

To deactivate:  conda deactivate

In [1]:
pip install faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 13.0 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 10.4 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [faiss-cpu]
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install numpy requests

  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
  Using cached urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached certifi-2025.8.3-py3-none-any.whl.metadata (2.4 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.5.0-py3-none-any.whl (129 kB)
Using cached certifi-2025.8.3-py3-none-any.whl (161 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [requests]
Note: you may need to restart the kernel to use updated packages.


In [4]:
# FAISS is installed and now we require data. Here we just copy from a website. But we can use any other unstructured source of data like pdf, json

data = """  General research interests topics are Wireless Communication, Cooperative Cognitive Communication, Wireless Sensor Networks (WSNs), 
and Internet of Things (IoT). Currently, I am involved with secure wireless communication for the future generation networks using physical 
layer security techniques.

Doctoral Thesis 

Research Topic: Physical Layer Security for V2X-enabled Cooperative and Cognitive Relay Networks.

Supervisor: Dr. Suneel Yadav, Assistant Professor, IIIT Allahabad.

Brief Overview: Cooperative vehicular relaying networks (CVRNs) support various key intelligent transportation 
application services such as traffic management, payment services, infotainment etc. These CVRNs are paving the 
way for the development of a new paradigm called Internet of Vehicles (IoV). Such networks will require the information exchange 
to occur between the vehicles, infrastructure, users, and the Internet mostly over an open and vulnerable wireless medium. 
Thus securing the transmissions at the physical layer becomes essential. The objective in this work is to investigate the 
potential benefits of physical layer security (PHY-security) for providing information security in CVRNs under cognitive and non-cognitive scenarios.

M.Tech. Thesis

Research Topic: Intra-Cluster Community Mechanism for Energy Efficiency and Data Resolution in Wireless Sensor Network.

Supervisor: Dr. K.K. Pattanaik, Associate Professor, ABV-IIITM Gwalior.

Brief Overview: Clustering scheme is effective in large scale densely deployed Wireless Sensor Networks (WSN). 
Performing data aggregation at cluster head (CH) or compressing the data traffic originating from spatially correlated nodes 
does not resolve the redundant traffic within the cluster and causes energy wastage. Selecting one node at a time among the 
correlated ones affects the data resolution. The novelty of this work lied in eliminating the redundant transmissions 
through designing a novel community of spatially correlated nodes within the cluster and then using average consensus 
mechanism for an efficient data aggregation. The above mechanism resulted in considerable reduction of redundant traffic, energy consumption, channel 
contention and better GTS slot assignment while preserving data resolution. The above system was verified through both mathematical and 
simulation in OPNET Network simulator.

"""

Lets now break down this data into small small fragments of some fixed size. We need to keep some overlap between these segments

In [6]:
clean_data = data.strip()

# The above step removes the leading and trailing spaces from the data

2377

In [7]:
# Breaking the data into small chunks of fixed size with some overlap
max_char = 400
overlap = 100

# Overlap is required to maintain the relatisonship and maintain some context between the segments

chunks = []

i = 0

while i < len(clean_data):
    piece = clean_data[i:i+max_char]
    chunks.append(piece)
    i += max_char - overlap


In [9]:
chunks

['General research interests topics are Wireless Communication, Cooperative Cognitive Communication, Wireless Sensor Networks (WSNs), \nand Internet of Things (IoT). Currently, I am involved with secure wireless communication for the future generation networks using physical \nlayer security techniques.\n\nDoctoral Thesis \n\nResearch Topic: Physical Layer Security for V2X-enabled Cooperative and Cognitiv',
 '\n\nDoctoral Thesis \n\nResearch Topic: Physical Layer Security for V2X-enabled Cooperative and Cognitive Relay Networks.\n\nSupervisor: Dr. Suneel Yadav, Assistant Professor, IIIT Allahabad.\n\nBrief Overview: Cooperative vehicular relaying networks (CVRNs) support various key intelligent transportation \napplication services such as traffic management, payment services, infotainment etc. These CVRNs are ',
 'pplication services such as traffic management, payment services, infotainment etc. These CVRNs are paving the \nway for the development of a new paradigm called Internet of

In [10]:
# Next action is to obtain the embedding or vector space

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-37b9fff3358867bfbeab3928b39f637bb00e12d253459000b0794bd0c4177b7f"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding


In [12]:
for i in chunks:
    embedding = generate_embeddings(i)
    print(embedding)
    print(embedding.shape)
    print("\n")

[ 0.03319761 -0.01910552 -0.00547118 ...  0.00032168 -0.00030704
  0.02384648]
(1536,)


[ 0.03735477 -0.02227229 -0.03486598 ... -0.00266737  0.015094
  0.02302123]
(1536,)


[ 0.02712595 -0.01438375  0.05812704 ... -0.00173069 -0.00612218
  0.03404199]
(1536,)


[ 0.0562048   0.03134195 -0.00875073 ... -0.01135816 -0.0010601
  0.0051227 ]
(1536,)


[ 0.05124796  0.03914956  0.00615395 ... -0.00534215  0.02914613
  0.01050099]
(1536,)


[ 0.0493216  -0.01986492  0.05524438 ...  0.00437657 -0.01371937
  0.00391467]
(1536,)


[ 0.04729202 -0.02137262  0.04288136 ... -0.00247589  0.00701076
  0.01370162]
(1536,)


[ 0.0173463  -0.01873289  0.02283721 ... -0.00226188  0.02077119
 -0.00877021]
(1536,)




In [13]:
emb_list = []
meta = []
for idx, chunk in enumerate(chunks):
    vec = generate_embeddings(chunk)
    emb_list.append(vec.astype('float32'))
    meta.append({"chunk_id": idx, "chunk": chunk})

In [14]:
emb_list

[array([ 0.03319762, -0.01910552, -0.00547118, ...,  0.00032168,
        -0.00030704,  0.02384648], shape=(1536,), dtype=float32),
 array([ 0.03734194, -0.02225533, -0.03487552, ..., -0.00268827,
         0.0150866 ,  0.02299295], shape=(1536,), dtype=float32),
 array([ 0.02712595, -0.01438375,  0.05812704, ..., -0.00173069,
        -0.00612218,  0.03404199], shape=(1536,), dtype=float32),
 array([ 0.0562048 ,  0.03134195, -0.00875072, ..., -0.01135816,
        -0.0010601 ,  0.0051227 ], shape=(1536,), dtype=float32),
 array([ 0.05124796,  0.03914956,  0.00615394, ..., -0.00534215,
         0.02914613,  0.01050099], shape=(1536,), dtype=float32),
 array([ 0.0493216 , -0.01986491,  0.05524438, ...,  0.00437657,
        -0.01371937,  0.00391467], shape=(1536,), dtype=float32),
 array([ 0.04729202, -0.02137262,  0.04288136, ..., -0.00247589,
         0.00701076,  0.01370162], shape=(1536,), dtype=float32),
 array([ 0.01731944, -0.01869224,  0.02283836, ..., -0.002262  ,
         0.0207583

In [15]:
meta

[{'chunk_id': 0,
  'chunk': 'General research interests topics are Wireless Communication, Cooperative Cognitive Communication, Wireless Sensor Networks (WSNs), \nand Internet of Things (IoT). Currently, I am involved with secure wireless communication for the future generation networks using physical \nlayer security techniques.\n\nDoctoral Thesis \n\nResearch Topic: Physical Layer Security for V2X-enabled Cooperative and Cognitiv'},
 {'chunk_id': 1,
  'chunk': '\n\nDoctoral Thesis \n\nResearch Topic: Physical Layer Security for V2X-enabled Cooperative and Cognitive Relay Networks.\n\nSupervisor: Dr. Suneel Yadav, Assistant Professor, IIIT Allahabad.\n\nBrief Overview: Cooperative vehicular relaying networks (CVRNs) support various key intelligent transportation \napplication services such as traffic management, payment services, infotainment etc. These CVRNs are '},
 {'chunk_id': 2,
  'chunk': 'pplication services such as traffic management, payment services, infotainment etc. These 

In [16]:
type(emb_list)  # numpy array of float32

list

We need to convert the list type of data to numpy vector format

In [18]:
xb = np.vstack(emb_list)

We need now to send this data to FAISS for similarity search

In [21]:
import faiss
faiss.normalize_L2(xb)  # should be 1.0

In [23]:
d = xb.shape[1]

In [28]:
index = faiss.IndexFlatIP(d)  # Using Inner Product (IP) for cosine similarity d =1536
index.add(xb)  # add vectors to the index

By above, we have stored above data. The above two lines are only storing data inside FAISS. 

index = faiss.IndexFlatIP(d)  # Using Inner Product (IP) for cosine similarity d =1536
index.add(xb)  # add vectors to the 


All other steps were just data preprocessing

In [29]:
# Presently the data is avialable in a memory and now this data has to be stored ij a file

index_path = "index_anshul.faiss"
meta_path = "meta_anshul.jsonl"

In [30]:
faiss.write_index(index, index_path)


In [31]:
import json, os


In [33]:
with open(meta_path, 'w') as f:
    for item in meta:
        f.write(json.dumps(item) + "\n")

Now, the files are created and can be used whenever, requird. Next steps is "SEARCHING"

In [39]:
query = "What was anshul thesis topic in M.Tech?"
xq = generate_embeddings(query).astype('float32').reshape(1, -1)
faiss.normalize_L2(xq)  # should be 1.0
index.search(xq, k=5)  # search the top k, k represent topmost k results based on similarity

(array([[0.50643706, 0.44751012, 0.41063118, 0.40908074, 0.28474218]],
       dtype=float32),
 array([[4, 1, 0, 3, 7]]))

To understand normalization

In [40]:
test = np.array([[1, 2, 34, 5, 6]], dtype='float32')

In [41]:
test

array([[ 1.,  2., 34.,  5.,  6.]], dtype=float32)

In [43]:
np.linalg.norm(test)

np.float32(34.957115)

In [44]:
faiss.normalize_L2(test)  # should be 1.0

In [45]:
np.linalg.norm(test)

np.float32(1.0)

np.linalg.norm(test)----------cALCULATES THE NORM FOR THE VECTOR Test.

faiss.normalize_L2(test)----------- Normalizes

after applying faiss.normalize_L2(test), if we apply and check norm with np.linalg.norm(test), we will get 1

Some other data base:

1. Qdrant Vector Database
2. Chromadb
3. Weaviate
2. Pinecone