In [1]:
pip install qdrant-client

  Using cached anyio-4.10.0-py3-none-any.whl.metadata (4.0 kB)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 7.3 MB/s eta 0:00:00a 0:00:01
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 9.9 MB/s eta 0:00:00
Using cached anyio-4.10.0-py3-none-any.whl (107 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/16 [qdrant-client]0m [qdrant-client]
Note: you may need to restart the kernel to use updated packages.


In [2]:
from qdrant_client import QdrantClient

qdrant_client = QdrantClient(
    url="https://2755c8ef-5949-43cb-a09f-6b8534a8fe75.us-east4-0.gcp.cloud.qdrant.io:6333", 
    api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.m2DCnzCd7DR2xhK4vLGRrqNIxiXtVTZIl9MzQ_BKe28",
)

print(qdrant_client.get_collections())

collections=[]


In [3]:
collection_name = "anshul_research"


In [31]:
from qdrant_client import models
qdrant_client.recreate_collection(
    collection_name=collection_name,
    vectors_config=models.VectorParams(
        size=1536,distance=models.Distance.COSINE,
    )
)


/var/folders/1c/86r17r4j6bv10y5ds690bz3c0000gn/T/ipykernel_58805/874220354.py:2: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(


True

Now, we wnat to store our data into this collection

In [32]:
points = []


In [33]:
data = """  General research interests topics are Wireless Communication, Cooperative Cognitive Communication, Wireless Sensor Networks (WSNs), 
and Internet of Things (IoT). Currently, I am involved with secure wireless communication for the future generation networks using physical 
layer security techniques.

Doctoral Thesis 

Research Topic: Physical Layer Security for V2X-enabled Cooperative and Cognitive Relay Networks.

Supervisor: Dr. Suneel Yadav, Assistant Professor, IIIT Allahabad.

Brief Overview: Cooperative vehicular relaying networks (CVRNs) support various key intelligent transportation 
application services such as traffic management, payment services, infotainment etc. These CVRNs are paving the 
way for the development of a new paradigm called Internet of Vehicles (IoV). Such networks will require the information exchange 
to occur between the vehicles, infrastructure, users, and the Internet mostly over an open and vulnerable wireless medium. 
Thus securing the transmissions at the physical layer becomes essential. The objective in this work is to investigate the 
potential benefits of physical layer security (PHY-security) for providing information security in CVRNs under cognitive and non-cognitive scenarios.

M.Tech. Thesis

Research Topic: Intra-Cluster Community Mechanism for Energy Efficiency and Data Resolution in Wireless Sensor Network.

Supervisor: Dr. K.K. Pattanaik, Associate Professor, ABV-IIITM Gwalior.

Brief Overview: Clustering scheme is effective in large scale densely deployed Wireless Sensor Networks (WSN). 
Performing data aggregation at cluster head (CH) or compressing the data traffic originating from spatially correlated nodes 
does not resolve the redundant traffic within the cluster and causes energy wastage. Selecting one node at a time among the 
correlated ones affects the data resolution. The novelty of this work lied in eliminating the redundant transmissions 
through designing a novel community of spatially correlated nodes within the cluster and then using average consensus 
mechanism for an efficient data aggregation. The above mechanism resulted in considerable reduction of redundant traffic, energy consumption, channel 
contention and better GTS slot assignment while preserving data resolution. The above system was verified through both mathematical and 
simulation in OPNET Network simulator.

"""


In [34]:
clean_data = data.strip()

In [35]:
# Breaking the data into small chunks of fixed size with some overlap
max_char = 400
overlap = 100

# Overlap is required to maintain the relatisonship and maintain some context between the segments

chunks = []

i = 0

while i < len(clean_data):
    piece = clean_data[i:i+max_char]
    chunks.append(piece)
    i += max_char - overlap


In [36]:
# Next action is to obtain the embedding or vector space

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-37b9fff3358867bfbeab3928b39f637bb00e12d253459000b0794bd0c4177b7f"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding


In [37]:
emb = []
for i in chunks:
    emb.append(generate_embeddings(i))

In [38]:
emb

[array([ 0.03321834, -0.01909401, -0.00553367, ...,  0.00031077,
        -0.00029443,  0.02386751], shape=(1536,)),
 array([ 0.03733321, -0.02226165, -0.03489042, ..., -0.00265164,
         0.01508308,  0.02301062], shape=(1536,)),
 array([ 0.02712595, -0.01438375,  0.05812704, ..., -0.00173069,
        -0.00612218,  0.03404199], shape=(1536,)),
 array([ 0.0562048 ,  0.03134195, -0.00875073, ..., -0.01135816,
        -0.0010601 ,  0.0051227 ], shape=(1536,)),
 array([ 0.05124796,  0.03914956,  0.00615395, ..., -0.00534215,
         0.02914613,  0.01050099], shape=(1536,)),
 array([ 0.0493216 , -0.01986492,  0.05524438, ...,  0.00437657,
        -0.01371937,  0.00391467], shape=(1536,)),
 array([ 0.04729202, -0.02137262,  0.04288136, ..., -0.00247589,
         0.00701076,  0.01370162], shape=(1536,)),
 array([ 0.01731944, -0.01869224,  0.02283836, ..., -0.002262  ,
         0.02075837, -0.00875679], shape=(1536,))]

In [39]:
embeddings = np.array(emb)

In [40]:
embeddings

array([[ 0.03321834, -0.01909401, -0.00553367, ...,  0.00031077,
        -0.00029443,  0.02386751],
       [ 0.03733321, -0.02226165, -0.03489042, ..., -0.00265164,
         0.01508308,  0.02301062],
       [ 0.02712595, -0.01438375,  0.05812704, ..., -0.00173069,
        -0.00612218,  0.03404199],
       ...,
       [ 0.0493216 , -0.01986492,  0.05524438, ...,  0.00437657,
        -0.01371937,  0.00391467],
       [ 0.04729202, -0.02137262,  0.04288136, ..., -0.00247589,
         0.00701076,  0.01370162],
       [ 0.01731944, -0.01869224,  0.02283836, ..., -0.002262  ,
         0.02075837, -0.00875679]], shape=(8, 1536))

In [41]:
points = []

for idx, (chunk,emb) in enumerate(zip(chunks, embeddings)):
    points.append(models.PointStruct(
        id=idx,
        vector=emb.astype("float32").tolist(),
        payload={"text": chunk}
    ))

In [42]:
points

[PointStruct(id=0, vector=[0.03321834281086922, -0.019094007089734077, -0.005533665418624878, 0.018407408148050308, -0.04054206982254982, -0.0021892173681408167, 0.03683661296963692, 0.018243931233882904, 0.014963511377573013, -0.014865425415337086, -0.03653145581483841, 0.010320790112018585, -0.06643668562173843, -0.001573457382619381, 0.03688020631670952, -0.007950386963784695, 0.00035011128056794405, 0.01065319124609232, 0.04025870934128761, 0.0010653191711753607, 0.01741565205156803, 0.01282742340117693, 0.003735428676009178, -0.048301734030246735, -0.038188014179468155, -0.03694559633731842, 0.04315768554806709, 0.07829415053129196, 0.019028617069125175, 0.0435500293970108, 0.027246015146374702, -0.02500094287097454, -0.06403902918100357, -0.0026701095048338175, -0.03910348191857338, 0.0036727627739310265, -0.046078458428382874, -0.010146415792405605, -0.009285441599786282, 0.016936123371124268, 0.033872246742248535, -0.010331688448786736, -0.026134377345442772, 0.0112580535933375

In [43]:
# Send the data to Cloud data base
qdrant_client.upsert(
    collection_name=collection_name,
    points=points
)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

In [51]:
query = "What is Anshul PhD topic?"

In [52]:
query_response = generate_embeddings(query)

In [53]:
query_vec = np.array(query_response).astype("float32")

In [54]:
qdrant_client.search(
    collection_name=collection_name,
    query_vector=query_vec,
    limit=2,
    with_payload=True
)


/var/folders/1c/86r17r4j6bv10y5ds690bz3c0000gn/T/ipykernel_58805/4294887589.py:1: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  qdrant_client.search(


[ScoredPoint(id=1, version=0, score=0.45089543, payload={'text': '\n\nDoctoral Thesis \n\nResearch Topic: Physical Layer Security for V2X-enabled Cooperative and Cognitive Relay Networks.\n\nSupervisor: Dr. Suneel Yadav, Assistant Professor, IIIT Allahabad.\n\nBrief Overview: Cooperative vehicular relaying networks (CVRNs) support various key intelligent transportation \napplication services such as traffic management, payment services, infotainment etc. These CVRNs are '}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=0, version=0, score=0.40305996, payload={'text': 'General research interests topics are Wireless Communication, Cooperative Cognitive Communication, Wireless Sensor Networks (WSNs), \nand Internet of Things (IoT). Currently, I am involved with secure wireless communication for the future generation networks using physical \nlayer security techniques.\n\nDoctoral Thesis \n\nResearch Topic: Physical Layer Security for V2X-enabled Cooperative and Cognitiv'