Pinecone is also a vector database, a managed database which is going to giver us a complete industry grade apploication building facilities

In [1]:
pip install pinecone

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.6/587.6 kB 14.2 MB/s eta 0:00:00
  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [pinecone]3/4 [pinecone]
Note: you may need to restart the kernel to use updated packages.


In [3]:
from pinecone import Pinecone

pc = Pinecone(api_key="pcsk_ezH4s_PtWsQ5vUguiisVEXkWjYJn1mkMiheuUkBQJpshSgJFdXRLzyJvKyctCDF85KoJr")
index = pc.Index("anshulstory")

In [4]:
# Now, we first prepare the dat

texts = """  General research interests topics are Wireless Communication, Cooperative Cognitive Communication, Wireless Sensor Networks (WSNs), 
and Internet of Things (IoT). Currently, I am involved with secure wireless communication for the future generation networks using physical 
layer security techniques.

Doctoral Thesis 

Research Topic: Physical Layer Security for V2X-enabled Cooperative and Cognitive Relay Networks.

Supervisor: Dr. Suneel Yadav, Assistant Professor, IIIT Allahabad.

Brief Overview: Cooperative vehicular relaying networks (CVRNs) support various key intelligent transportation 
application services such as traffic management, payment services, infotainment etc. These CVRNs are paving the 
way for the development of a new paradigm called Internet of Vehicles (IoV). Such networks will require the information exchange 
to occur between the vehicles, infrastructure, users, and the Internet mostly over an open and vulnerable wireless medium. 
Thus securing the transmissions at the physical layer becomes essential. The objective in this work is to investigate the 
potential benefits of physical layer security (PHY-security) for providing information security in CVRNs under cognitive and non-cognitive scenarios.

M.Tech. Thesis

Research Topic: Intra-Cluster Community Mechanism for Energy Efficiency and Data Resolution in Wireless Sensor Network.

Supervisor: Dr. K.K. Pattanaik, Associate Professor, ABV-IIITM Gwalior.

Brief Overview: Clustering scheme is effective in large scale densely deployed Wireless Sensor Networks (WSN). 
Performing data aggregation at cluster head (CH) or compressing the data traffic originating from spatially correlated nodes 
does not resolve the redundant traffic within the cluster and causes energy wastage. Selecting one node at a time among the 
correlated ones affects the data resolution. The novelty of this work lied in eliminating the redundant transmissions 
through designing a novel community of spatially correlated nodes within the cluster and then using average consensus 
mechanism for an efficient data aggregation. The above mechanism resulted in considerable reduction of redundant traffic, energy consumption, channel 
contention and better GTS slot assignment while preserving data resolution. The above system was verified through both mathematical and 
simulation in OPNET Network simulator."""

In [5]:
# Now, data set has to be converted into embeddings. For embeddings we have many models to chose from.

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-37b9fff3358867bfbeab3928b39f637bb00e12d253459000b0794bd0c4177b7f"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding



In [6]:
#Now, using the above embedding function and the data set we need to convert the entire data set and convert it into embeddings.

embeddings = []
for text in texts.split("\n"):
    if text.strip():  # Skip empty lines
        embedding = generate_embeddings(text)
        embeddings.append(embedding)


In [20]:
docs = [text for text in texts.split("\n") if text.strip()]
records = []
for i in range(len(embeddings)):
    if text.strip():
        records.append((str(i), embeddings[i], {"text": docs[i]}))

In [21]:
records

[('0',
  array([ 0.03394453,  0.00196782,  0.04239005, ...,  0.01197223,
         -0.00086427,  0.03570788], shape=(1536,)),
  {'text': '  General research interests topics are Wireless Communication, Cooperative Cognitive Communication, Wireless Sensor Networks (WSNs), '}),
 ('1',
  array([ 0.00897844, -0.024341  , -0.00549059, ..., -0.00908936,
          0.01050052,  0.00476036], shape=(1536,)),
  {'text': 'and Internet of Things (IoT). Currently, I am involved with secure wireless communication for the future generation networks using physical '}),
 ('2',
  array([ 0.00576188,  0.03124992,  0.03090334, ..., -0.04785685,
         -0.01939401, -0.01157431], shape=(1536,)),
  {'text': 'layer security techniques.'}),
 ('3',
  array([ 0.02384244,  0.03676933, -0.07426185, ..., -0.00766122,
          0.00069529, -0.01013586], shape=(1536,)),
  {'text': 'Doctoral Thesis '}),
 ('4',
  array([ 0.03825732, -0.03073993, -0.03550414, ...,  0.01541784,
          0.00411482,  0.03485774], shape=(

In [22]:
index.upsert(vectors=records)

{'upserted_count': 23}

In [23]:
# Now, we have to query the data from the vector database.

query = "Who is Anshul Pandey?"

In [24]:
query_embedding = generate_embeddings(query).tolist()

In [26]:
index.query(vector=query_embedding, top_k=3, include_metadata=True)

{'matches': [{'id': '5',
              'metadata': {'text': 'Supervisor: Dr. Suneel Yadav, Assistant '
                                   'Professor, IIIT Allahabad.'},
              'score': 0.29521814,
              'values': []},
             {'id': '14',
              'metadata': {'text': 'Supervisor: Dr. K.K. Pattanaik, Associate '
                                   'Professor, ABV-IIITM Gwalior.'},
              'score': 0.233063817,
              'values': []},
             {'id': '12',
              'metadata': {'text': 'M.Tech. Thesis'},
              'score': 0.203203157,
              'values': []}],
 'namespace': '',
 'usage': {'read_units': 1}}